- name: Install mariadb-server package
  ansible.builtin.package:
    name: mariadb-server
    state: present

- name: Ensure mariadb service is enabled and started
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true

- name: Wait for MariaDB socket to appear
  ansible.builtin.wait_for:
    path: "{{ mysql_socket }}"
    state: started
    timeout: 60

- name: Install Python MySQL library via APT
  ansible.builtin.apt:
    name: python3-pymysql
    state: present
    update_cache: yes

- name: Create database user (connect via unix socket as root)
  ansible.builtin.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL'
    host: localhost
    state: present
    login_unix_socket: "{{ mysql_socket }}"

- name: Create the database (connect via unix socket as root)
  ansible.builtin.mysql_db:
    name: "{{ db_name }}"
    state: present
    login_unix_socket: "{{ mysql_socket }}"
    