---
- name: Install mariadb-server package
  ansible.builtin.package:
    name: "mariadb-server"
    state: present
  become: true

- name: Ensure mariadb service is enabled and started
  ansible.builtin.service:
    name: "mariadb"
    state: started
    enabled: true
  become: true

- name: Ensure Python 3 and pip are installed
  apt:
    name:
      - python3
      - python3-pip
      - python3-dev
      - default-libmysqlclient-dev
      - build-essential
    state: present
    update_cache: yes

- name: Install PyMySQL for Ansible MySQL modules
  pip:
    name: PyMySQL
    executable: pip3

- name: Create a database
  ansible.builtin.mysql_db:
    name: "{{ db_name }}"
    state: present
  become: true